// DO NOT EDIT THIS FILE. This file auto-generated, use `npm run sync-icons` to update icons
import type { SVGProps } from 'react';
import React from 'react';

const IconChevonRight: React.FC<SVGProps<SVGSVGElement>> = props => {
  return (
    <svg
      aria-hidden="true"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 6 10"
      {...props}
    >
      <path
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m1 9 4-4-4-4"
      />
    </svg>
  );
};

export default IconChevonRight;
